### ISSUE TITLE
我想请教下 ，我在react中怎么引用这个

### ISSUE THREAD

**Issue by Zhangliquan94** [deyihu/maptalks-deckgl#2]
[项目地址](https://github.com/Zhangliquan94/ycyfans-map)

**Comment by deyihu** [comment]
@Zhangliquan94 

谢谢提问题，这个插件在基于node的模块化开发中的确是有问题的，然后我去[deck.gl](http://deck.gl/#/documentation/getting-started/using-standalone?section=using-deck-gl-core)的网站看了一下，官方说DeckGL 适用与 script 脚本标签直接引入的方式和react 环境中，Deck适用于script 脚本标签和模块化，而我的这个插件原来是基于DeckGL的，所以在
script直接引入的这种方式下是没有问题，但是在基于node的模块化开发中的确是有问题的，现在我更新了基于Deck,所以现在不管是直接script标签引入的方式[示例](https://deyihu.github.io/src/maptalks-deckgl/examples/)，还是模块这种开发都是可以的.
我的做的基于webpack的 [例子](https://github.com/deyihu/webpacktest/blob/master/src/index.js)


另外这个和使用react还是vue等框架是无关的，只是react环境下，deck.gl直接提供了DeckGL拆箱直接使用的组件而已


而且我的这个插件和 https://github.com/sakitam-gis/maptalks.deckgl 这个插件实现方式是完全不一样的，
我这个是基于 dom渲染的，新建了一个div容器，将deck.gl的容器放在里面，这个layer的层级是高于vectorlayer的，而  https://github.com/sakitam-gis/maptalks.deckgl  这个插件是vectorlayer一样的，利用canvas创建了一个webgl上下文传递给deck.gl，

虽然两个都是将deck.gl作为图层加入到map对象上，但是两者的表现完全不同，我的这个插件如果你在地图添加点线面等，你会发现deck.gl这个图层永远在点线面所在图层（vectorlayer）的上面，但是https://github.com/sakitam-gis/maptalks.deckgl  这个插件是和vectorlayer图层层级一样的，可以调整zindex来确定他们的上下层级，

所以使用的时候请注意，从实现的角度https://github.com/sakitam-gis/maptalks.deckgl 这个实现的更好
